### ISSUE TITLE
Following this guide produces an error

### ISSUE THREAD

**Issue by yoooee** [johnpapa/gulp-patterns#106]
When I go through the following steps:
$ npm install
$ bower install
$ tsd install -r -o --save
$ gulp serve-dev

The final step results in the following error: 
gulp-patterns] Watching files...
About to crank up node
PORT=7203
NODE_ENV=dev
** DEV **
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1129:14)
    at listen (net.js:1155:10)
    at Server.listen (net.js:1240:5)
    at EventEmitter.listen (/##########/gulpTest/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/##########/gulpTest/src/server/app.js:63:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
[10:15:38] *** nodemon crashed: script crashed for some reason
[10:15:38] [nodemon] app crashed - waiting for file changes before starting...

NOTE: I replaced the path that was displayed in the output with ##########.

**Comment by godhand1607** [comment]
Looks like your machine's port 7203 is already used. Try changing it
